/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;

/**
 *
 * @author eduardo-b
 */
public class PanelColaForm extends javax.swing.JPanel {
    // instanciar clase Logica de la cola
    private ColasDinamicas.ListaCola cola = new ColasDinamicas.ListaCola();
    // modelo para manejar los visuales
    private javax.swing.DefaultListModel<String> modeloCola = new javax.swing.DefaultListModel<>();

    /**
     * Creates new form PanelColaForm
     */

    private Ventana ventanaPadre;

    public PanelColaForm(Ventana ventanaPadre) {
        this.ventanaPadre = ventanaPadre;

        initComponents();
        jList1.setModel(modeloCola);
    }

    private void actualizarVistaCola() {
        modeloCola.clear();
        ColasDinamicas.Nodo temp = cola.P;

        while (temp != null) {
            modeloCola.addElement(String.valueOf(temp.info));
            temp = temp.liga;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Insertar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Volver al menu");
        jButton3.setActionCommand("Volver al Menu");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        jLabel1.setText("Colas Dinamicas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(327, 327, 327)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTextField1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 234,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton1)
                                                                .addGap(175, 175, 175)
                                                                .addComponent(jButton2))
                                                        .addComponent(jScrollPane1)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                751, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(568, 568, 568)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 285,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(383, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(jButton3)
                                .addContainerGap(146, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        ventanaPadre.mostrarPanel("Menu");
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        try {
            int valor = Integer.parseInt(jTextField1.getText());
            cola.insertarInicio(valor);
            jTextField1.setText("");
            actualizarVistaCola();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "ingrese solo valores enteros", "ERROR",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

        Integer eliminado = cola.quitarFinal();
        if (eliminado != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Se eliminó el valor: " + eliminado);
            actualizarVistaCola();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay datos en la lista", "ERROR",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
